# Generated by Django 5.2.2 on 2025-06-05 16:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_scanned_block', models.BigIntegerField(default=0)),
                ('last_scan_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_images_found', models.IntegerField(default=0)),
                ('scan_in_progress', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Scan statuses',
            },
        ),
        migrations.CreateModel(
            name='ArbiusImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_hash', models.CharField(db_index=True, max_length=66, unique=True)),
                ('task_id', models.CharField(db_index=True, max_length=66)),
                ('block_number', models.BigIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('cid', models.CharField(db_index=True, max_length=100)),
                ('ipfs_url', models.URLField()),
                ('image_url', models.URLField()),
                ('miner_address', models.CharField(max_length=42)),
                ('owner_address', models.CharField(blank=True, max_length=42, null=True)),
                ('gas_used', models.BigIntegerField(blank=True, null=True)),
                ('discovered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_accessible', models.BooleanField(default=True)),
                ('last_checked', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='gallery_arb_timesta_2cfe8d_idx'), models.Index(fields=['cid'], name='gallery_arb_cid_3b92aa_idx'), models.Index(fields=['transaction_hash'], name='gallery_arb_transac_ebf912_idx')],
            },
        ),
    ]
