# Generated by Django 5.2.2 on 2025-06-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbiusimage',
            name='ipfs_gateway',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
