# Generated by Django 5.2.2 on 2025-06-06 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_arbiusimage_ipfs_gateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbiusimage',
            name='input_parameters',
            field=models.JSONField(blank=True, help_text='Full input parameters including prompt and other settings', null=True),
        ),
        migrations.AddField(
            model_name='arbiusimage',
            name='model_id',
            field=models.CharField(blank=True, help_text='The AI model used to generate this image', max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='arbiusimage',
            name='prompt',
            field=models.TextField(blank=True, help_text='The prompt used to generate this image', null=True),
        ),
    ]
