# Generated by Django 5.2.2 on 2025-06-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_arbiusimage_input_parameters_arbiusimage_model_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbiusimage',
            name='solution_provider',
            field=models.CharField(default='0x0000000000000000000000000000000000000000', help_text='Address of the miner who provided the solution/image', max_length=42),
        ),
        migrations.AddField(
            model_name='arbiusimage',
            name='task_submitter',
            field=models.CharField(blank=True, help_text='Address of the user who originally submitted the task/prompt', max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='arbiusimage',
            name='miner_address',
            field=models.CharField(blank=True, help_text='DEPRECATED: Use solution_provider instead', max_length=42, null=True),
        ),
    ]
