# Generated by Django 5.2.2 on 2025-06-06 10:43

from django.db import migrations


def populate_solution_provider(apps, schema_editor):
    """Populate solution_provider field from existing miner_address data"""
    ArbiusImage = apps.get_model('gallery', 'ArbiusImage')
    
    # Update all existing records to use miner_address as solution_provider
    for image in ArbiusImage.objects.all():
        if image.miner_address and not image.solution_provider:
            image.solution_provider = image.miner_address
            image.save(update_fields=['solution_provider'])


def reverse_populate_solution_provider(apps, schema_editor):
    """Reverse migration - clear solution_provider field"""
    ArbiusImage = apps.get_model('gallery', 'ArbiusImage')
    ArbiusImage.objects.update(solution_provider='0x0000000000000000000000000000000000000000')


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_clarify_submitter_provider'),
    ]

    operations = [
        migrations.RunPython(populate_solution_provider, reverse_populate_solution_provider),
    ]
