# Generated by Django 5.2.2 on 2025-06-12 11:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_mineraddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinerTokenEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miner_address', models.CharField(db_index=True, max_length=42, unique=True)),
                ('total_aius_earned', models.DecimalField(decimal_places=18, default=0, max_digits=36)),
                ('total_aius_sold', models.DecimalField(decimal_places=18, default=0, max_digits=36)),
                ('total_usd_from_sales', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('first_earning_date', models.DateTimeField(blank=True, null=True)),
                ('last_earning_date', models.DateTimeField(blank=True, null=True)),
                ('last_sale_date', models.DateTimeField(blank=True, null=True)),
                ('last_analyzed', models.DateTimeField(blank=True, null=True)),
                ('needs_reanalysis', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-total_usd_from_sales'],
            },
        ),
        migrations.CreateModel(
            name='TokenTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_hash', models.CharField(db_index=True, max_length=66, unique=True)),
                ('from_address', models.CharField(db_index=True, max_length=42)),
                ('to_address', models.CharField(db_index=True, max_length=42)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=36)),
                ('block_number', models.BigIntegerField(db_index=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('gas_price', models.BigIntegerField(blank=True, null=True)),
                ('gas_used', models.BigIntegerField(blank=True, null=True)),
                ('is_sale', models.BooleanField(default=False)),
                ('sale_price_usd', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('exchange_address', models.CharField(blank=True, max_length=42, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['from_address', '-timestamp'], name='gallery_tok_from_ad_3f408c_idx'), models.Index(fields=['to_address', '-timestamp'], name='gallery_tok_to_addr_1fd686_idx'), models.Index(fields=['block_number'], name='gallery_tok_block_n_130037_idx'), models.Index(fields=['is_sale'], name='gallery_tok_is_sale_b32c64_idx')],
            },
        ),
    ]
